global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'discovery-jvm'
    static_configs:
      - targets: ['discovery-server:9404']
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):.*'
        target_label: 'instance'
        replacement: '$1'
        action: 'replace'
      - source_labels: [__address__]
        regex: '(.*):.*'
        target_label: 'name'       # <-- add this line
        replacement: '$1'
        action: 'replace'  
